# Technical configuration file for gyōza

executor: slurm
slurm-logdir: logs/SLURM_out
slurm-status-command: sacct
slurm-qos: cpu-normal

# IMPORTANT - EDIT WHAT FOLLOWS!
default-resources:
  - slurm_partition="acpu"
  - mem_mb=1024
  - runtime=30
  # - slurm_extra="--mail-type=FAIL --mail-user=<YOUR-EMAIL-ADDRESS>"

# Dynamic allocation of rule-specific resources
# Resources for rule generate_mutants is handled dynamically in the smk file based on config entry
# The following was optimized from internal benchmarking
# Resources allocated should prevent overallocation but might not be enough at first attempt
set-resources:
  fastp:
    mem_mb: min(10240, max(int(0.02 * input.size_mb * attempt * 1024 + 0.99), 1024))
    runtime: max(int(0.01 * input.size_mb * attempt + 0.99), 1)
  compare_to_sequencing:
    mem_mb: min(10240, max(int(0.15 * input.size_mb * attempt * 1024 + 0.99), 2048))
    runtime: max(int(0.15 * input.size_mb * attempt + 0.99), 2)
  annotate_mutants:
    runtime: max(int(0.002 * input.size_mb * attempt + 0.99), 1)
  cutadapt:
    runtime: max(int(0.01 * input.size_mb * attempt + 0.99), 1)
  bbmerge:
    runtime: max(int(0.005 * input.size_mb * attempt + 0.99), 1)
  vsearch_fastx_uniques:
    runtime: max(int(0.0004 * input.size_mb * attempt + 0.99), 1)
  stats:
    runtime: max(int(0.001 * input.size_mb * attempt + 0.99), 1)
  parse_fasta:
    mem_mb: min(10240, max(int(0.002 * input.size_mb * attempt * 1024 + 0.99), 1024))
    runtime: max(int(0.002 * input.size_mb * attempt + 0.99), 1)
  process_read_counts:
    mem_mb: min(10240, max(int(0.2 * input.size_mb * attempt * 1024 + 0.99), 1024))
    runtime: max(int(0.5 * input.size_mb * attempt + 0.99), 1)

set-threads:
  fastp: 4
  bbmerge: 8
  vsearch: 1  # This command of vsearch is not multi-threaded

local-cores: 10
jobs: 500
max-jobs-per-second: 10
max-status-checks-per-second: 0.1  # May need to be much lower depending on cluster guidelines
latency-wait: 60
keep-going: True
rerun-incomplete: True
restart-times: 3
#printshellcmds: True
scheduler: greedy
use-conda: True
